server:
  port: 80
  servlet:
    context-path: /sell
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null #@JsonInclude(JsonInclude.Include.NON_NULL)这个注解的全局配置